#!/sbin/busybox sh
#
# CyanogenMod-SystemFormater for Samsung Galaxy S
# by codeworkx, coolya, finghin (c) 2010, GPLv2

# we make sure we have /sdcard mounted
sdcardmounted=`busybox grep emmc /proc/mounts`
if [ "$sdcardmounted" == "" ]; then
      # mount sdcard
      mkdir /mnt/emmc
      busybox mount -t vfat /dev/block/mmcblk0p1 /mnt/emmc
fi

# everything is logged into /mnt/emmc/format_system.log
exec >> /mnt/emmc/format_system.log 2>&1

set -x
export PATH=/:/sbin:/system/xbin:/system/bin:$PATH

halt()
{
[ "$sdcardmounted" == "" ] && /tmp/busybox umount /mnt/emmc
exit 1
}

busybox cat <<EOF
########################################################################################
#
# Starting CyanogenMod-SystemFormater
# `busybox date`
#
########################################################################################
EOF

# first, unmount to be sure
busybox umount -l /dev/block/stl9

# fix mtab errors
busybox rm -rf /etc
busybox mkdir /etc
busybox ln -s /proc/mounts /etc/mtab

# format system
dd if=/dev/zero of=/dev/block/stl9 bs=1024 count=10 || halt
mkfs.ext4 -q -L /system -b 4096 -m 0 -F /dev/block/stl9 || halt
tune2fs -o journal_data_writeback /dev/block/stl9

# do a filesystem check
fsck.ext4 -pf /dev/block/stl9

# mount system
busybox mount -t ext4 -o nosuid,nodev,noatime,nodiratime,errors=continue,nobh,data=writeback,barrier=0,noauto_da_alloc /dev/block/stl9 /system || halt

exit 0
