#!/sbin/busybox sh
#
# CyanogenMod-FilesystemConverter for Samsung Galaxy S
# backup a partition, format, and restore
# by codeworkx, coolya, finghin (c) 2010, GPLv2
# based on z4mod by Elia Yehuda
#
version=1.0.0

# we make sure we have /mnt/emmc mounted
sdcardmounted=`busybox grep emmc /proc/mounts`
if [ "$sdcardmounted" == "" ]; then
      # mount /mnt/emmc
      mkdir /mnt/emmc
      busybox mount -t vfat /dev/block/mmcblk0p1 /mnt/emmc
fi

# everything is logged into /mnt/emmc/cyanogenmod.log
exec >> /mnt/emmc/cyanogenmod.log 2>&1

set -x
export PATH=/:/sbin:/system/xbin:/system/bin:$PATH

halt()
{
umount /${partition}
[ "$sdcardmounted" == "" ] && busybox umount /mnt/emmc
exit 1
}

busybox cat <<EOF
########################################################################################
#
# Starting CyanogenMod-FilesystemConverter-$version '$3' convert on /$1 (/dev/block/$2)
# `busybox date`
#
########################################################################################
EOF

partition="$1"
devblock=/dev/block/"$2"
filesystem="$3"

if [ "${filesystem:0:3}" == "ext" ]; then
        [ `busybox grep ${filesystem} /proc/filesystems` ] && format_cmd=mkfs.${filesystem}
elif [ "$filesystem" == "jfs" ]; then
	[ `busybox grep ${filesystem} /proc/filesystems` ] && format_cmd=mkfs.${filesystem}
elif [ "$filesystem" == "rfs" ]; then
        format_cmd=fat.format
else
      # defaulting to 'auto' - check which filesystem are supported
      [ `busybox grep jfs /proc/filesystems` ] && filesystem=jfs
      [ `busybox grep ext4 /proc/filesystems` ] && filesystem=ext4
      format_cmd=mkfs.${filesystem}
fi

# check we have all the tools needed
[ "${format_cmd}" == "" ] && halt
[ `busybox which /system/xbin/${format_cmd}` ] || halt

# fix mtab errors
busybox ln -s /proc/mounts /etc/mtab

# copy format binary to /sbin
busybox cp `busybox which /system/xbin/${format_cmd}` /sbin/

#
# Make sure target partition is mounted
#
    # first, unmount to be sure
    busybox umount -l /${partition}

    # try to mount partition as rfs
    busybox mount -t rfs ${devblock} /${partition}

    # otherwise mount partition as ext4
    if busybox [ -z "`busybox mount | busybox grep ${devblock} | busybox grep rfs`" ]; then
        /sbin/busybox mount -t ext4 ${devblock} /${partition}
    fi

    # otherwise mount partition as jfs
    if busybox [ -z "`busybox mount | busybox grep ${devblock} | busybox grep ext4`" ]; then
        /sbin/busybox mount -t jfs ${devblock} /${partition}
    fi


# get current filesystem
currentfs=`busybox grep "/${partition}" /proc/mounts | busybox awk '{print $3}'`
[ "${currentfs}" == "${filesystem}" ] && halt
# defaulting to rfs
[ "${currentfs}" == "" ] && currentfs="rfs"

# we unmount just to make sure target is not mounted already
busybox umount -l /${partition}

# do a filesystemcheck on partition
fsck.${currentfs} -f ${devblock}

# we must mount target with propriate mount parameters
if [ "${currentfs}" == "rfs" ]; then
      # mount using RFS mount parameters - otherwise it will be mounted as FAT, which is bad.
      busybox mount -t $currentfs ${devblock} /${partition} -o nosuid,nodev,check=no || halt
else
      # mount target as ext4/jfs
      busybox mount -t $currentfs ${devblock} /${partition} -o nosuid,nodev,noatime,nodiratime,errors=continue || halt
fi

# remove old backup if any
busybox rm -f /mnt/emmc/${partition}.cyanogenmod.tar

# check for free space (using such a complicated command to overcome a 'df' bug with long lines)
# get free space on /mnt/emmc
free_space=`busybox df /dev/block/mmcblk0p1 | busybox tail -n1 | busybox sed 's|/[^ ]*||g' | busybox awk '{print $3}'`
# get used space on target
backup_size=`busybox df ${devblock} | busybox tail -n1 | busybox sed 's|/[^ ]*||g' | busybox awk '{print $2}'`
[ $backup_size -ge $free_space ] && halt

# backup target - exit on failure
busybox tar cf /mnt/emmc/${partition}.cyanogenmod.tar /${partition}
# for debug:
busybox echo $?

# umount - exit on failure, no harm is done
busybox umount -l /${partition} || halt

# for 'data' partition we make sure the filesystem type is flagged in the partition table
if [ "${partition}" == "data" ]; then
# we change fs-type manually in the partition table
if [ "${filesystem}" == "rfs" ]; then
# flag partition as fat32 for rfs
echo -en "\x0C" | busybox dd of=/dev/block/mmcblk0 seek=$((0x1d2))
else
# flag partition as linux filesystem
echo -en "\x83" | busybox dd of=/dev/block/mmcblk0 seek=$((0x1d2))
fi
fi

# Format partition with optimized settings
if [ "${filesystem}" == "rfs" ]; then
      mountopt="llw,check=no,nosuid,nodev"
      ${format_cmd} -v -S 4096 -s 1 -F 32 ${devblock}
elif [ "${filesystem}" == "jfs" ]; then
      mountopt="nosuid,nodev,noatime,nodiratime,errors=continue"
      ${format_cmd} -L ${partition} -q ${devblock}
elif [ "${filesystem}" == "ext4" ]; then
      mountopt="nosuid,nodev,noatime,nodiratime,errors=continue,nobh,data=writeback,barrier=0,noauto_da_alloc"
      ${format_cmd} -q -L ${partition} -b 4096 -m 0 -F ${devblock}
      # tune the filesystem - check every 100 mounts or 30 days
      tune2fs -c 100 -i 30d -m 0 -o journal_data_writeback  ${devblock}
fi

# do a filesystemcheck on partition
fsck.${filesystem} -f ${devblock}

# mount the new filesystem - exit on failure
busybox mount -t ${filesystem} ${devblock} /${partition} -o $mountopt || halt

# this is for the logging...
busybox mount | busybox grep ${devblock}

# extract our data back to the new filesystem
busybox tar xf /mnt/emmc/${partition}.cyanogenmod.tar -C /
ret=$?
[ $ret == 0 ] && busybox rm /mnt/emmc/${partition}.cyanogenmod.tar

busybox mount -o remount,rw /system
busybox touch /system/etc/fstab
# remove entry if exists already
busybox sed '\,'$devblock',d' /system/etc/fstab
# add /system/etc/fstab proper info
echo "$devblock $filesystem $mountopt" >> /system/etc/fstab
busybox mount -o remount,ro /system

# umount
busybox umount ${devblock}
[ "$sdcardmounted" == "" ] && busybox umount /mnt/emmc

exit $ret
